import nodemailer from "nodemailer";

export async function sendEmailWithPdf(
  email: string,
  buffer: Buffer,
  filename: string
): Promise<void> {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "yourcognixemail@gmail.com",
      pass: "your-app-password",
    },
  });

  const mailOptions = {
    from: "CogniX <yourcognixemail@gmail.com>",
    to: email,
    subject: "Your Market Research Report",
    text: "Attached is your research report generated by CogniX AI.",
    attachments: [{ filename, content: buffer }],
  };

  await transporter.sendMail(mailOptions);
}
